### ISSUE TITLE
Battery status-based ON_AC uses faulty logic

### ISSUE THREAD

**Issue by luke-jr** [rickysarraf/laptop-mode-tools#115]
```sh
        if [ $FOUND_SYS_CLASS_POWER_SUPPLY_AC != 1 ] && [ $BATTERY_NOT_DISCHARGING = 1 ]; then
```

But `BATTERY_NOT_DISCHARGING` can only ever be set if `FOUND_SYS_CLASS_POWER_SUPPLY_AC` is also being set. Should `FOUND_SYS_CLASS_POWER_SUPPLY_AC=1` be moved inside the "Mains" check??

**Comment by rickysarraf** [comment]
This must be the effect of https://github.com/rickysarraf/laptop-mode-tools/issues/116

Wherein you don't have a usual power supply subsystem.

**Comment by rickysarraf** [comment]
Closing this issue, for #116
