### ISSUE TITLE
CPU consumption very high

### ISSUE THREAD

**Issue by NewbProgrammer101** [rickysarraf/laptop-mode-tools#117]
When booting with A/C plugged in, CPU is fine. 

But when unplugging A/C adapter, CPU goes at 60-100% for a short period of time. This does not happen when laptop_mode is uninstalled.

When plugging back in A/C adapter, CPU goes at 60-100% for a short period of time. This does not happen when laptop_mode is uninstalled.

When booting with battery, CPU is fine.

**Comment by rickysarraf** [comment]
This is working as expected. When State changes occur, LMT runs through all is modules and enters into relevant power system. 

Spike at that point is expected.
