### ISSUE TITLE
wrong gui path

### ISSUE THREAD

**Issue by Fabioamd87** [rickysarraf/laptop-mode-tools#124]
Hello,

I've just installed Laptop Mode Tools 1.72 by the ./install script on ubuntu 17.10 64bit but when i run lmt-config-gui I get:

```
fabio@a514:/usr/share/laptop-mode-tools$ lmt-config-gui
python3: can't open file '/usr/share/laptop-mode-tools/lmt.py': [Errno 2] No such file or directory
```

```
fabio@a514:/usr/share/laptop-mode-tools$ ls
LMT.py  module-helpers  modules
fabio@a514:/usr/share/laptop-mode-tools$
```
solved with a:

`fabio@a514:/usr/share/laptop-mode-tools$ sudo mv LMT.py lmt.py`

is there an uppercase mistake somewhere?

**Comment by rickysarraf** [comment]
Thank you for the report. Yes. There was  a case sensitive naming mistake.

**Comment by FrostKnight** [comment]
I just had the same problem, thank you for that solution fabio!
