### ISSUE TITLE
No module named PySide.QtGui

### ISSUE THREAD

**Issue by ghost** [rickysarraf/laptop-mode-tools#139]
> ~$ lmt-config-gui
> Traceback (most recent call last):
>   File "/usr/share/laptop-mode-tools/lmt.py", line 21, in <module>
>     from PySide.QtGui import (QWidget, QMessageBox, QVBoxLayout, QHBoxLayout,
> ImportError: No module named PySide.QtGui

GUI fails to open

Version: 1.7.1-2
OS: Linux Mint 19 Tara

**Comment by rickysarraf** [comment]
Please try with the latest, i.e. version `1.72`. `PySide` support was dropped some time back.

**Comment by rickysarraf** [comment]
No response back from reporter. Please re-open if issues persists
