### ISSUE TITLE
can't start lmt-config-gui

### ISSUE THREAD

**Issue by doomdevelop** [rickysarraf/laptop-mode-tools#144]
Surface Pro 2017 Ubuntu 18.10.
`pkexec /usr/sbin/lmt-config-gui
Using PyQt4
No protocol specified
lmt.py: cannot connect to X server :0`

Probably related to the changes ubuntu made for gui apps with root permission.
Any idea how I can fix the command ?

Thank you !

**Comment by rickysarraf** [comment]
I am sorry for the very late reply.

It could possibly be because of `Wayland`. But I am not sure but iirc the last time I had tested on `Wayland` too.

Here, on `Xorg`, it is working fine.

![image](https://user-images.githubusercontent.com/65480/58782421-2d504980-85fc-11e9-817d-827734f7de26.png)

**Comment by Higurashi3301** [comment]
Since Wayland doesn't allow graphical applications to run with sudo, you need to make it fallback to xwayland via `xhost si:localuser:root` and than you can run it normally with `sudo lmt-config-gui` (and to remove the fallback, type `xhost -si:localuser:root`).

**Comment by FrostKnight** [comment]
Could also be related to this:  https://github.com/rickysarraf/laptop-mode-tools/issues/124#issue-294213802

I had that issue a while back... ;)

**Comment by rickysarraf** [comment]
On today's Wayland implementation on KDE, this is working out of the box. The big major difference than what was initially reported is that this is now based on PyQT5. Not sure if that has a role to play or not, but this issue isn't valid on my Wayland setup.

![Screenshot_20210610_201858](https://user-images.githubusercontent.com/65480/121547195-8c39cc00-ca29-11eb-9e9c-7d85f1ffbb61.png)
