### ISSUE TITLE
LCD Brightness module causes a loop of harddrive syncs

### ISSUE THREAD

**Issue by jameh** [rickysarraf/laptop-mode-tools#148]
System log after unplugging my power cable: https://hastebin.com/uperedilev

Brightness of my lcd is lowered immediately.

I can hear harddrive activity every second in sync with those SCSI messages.

it stops after a bit, but it seems that if I replug the power before it is done vomitting those messages, the brightness is not updated right away - like it's causing laptop_mode to become unresponsive

I'm running Arch Linux. Here's my module config file for the LCD control:
https://hastebin.com/aqabilonir

EDIT:
Also, it seems to only happen when I unplug the cord, not when I plug it in.

**Comment by rickysarraf** [comment]
Hi... Your logs do not seem to be accessible. Can you please attach them directly to this task instead ?

**Comment by rickysarraf** [comment]
No response from reported. When you have the necessary information, please attach it to this bug report on Github. Remote location links are useless for the very reason, which is now, where I can't access them.
