### ISSUE TITLE
LCD brightness old standards

### ISSUE THREAD

**Issue by Thanatermesis** [rickysarraf/laptop-mode-tools#152]
The actual LCD brightness script is not very compatible with new structures I assume

The attached patch is a redesign of it, it may lack some extra checks but should make the brightness more compatible among more computers

It also includes:
* auto-detection of the brightness file to control
* percentage-based brightness values

[lcd-brightness-redesigned.gz](https://github.com/rickysarraf/laptop-mode-tools/files/3688584/lcd-brightness-redesigned.gz)

**Comment by rickysarraf** [comment]
Can you please create a PR instead ?

**Comment by rickysarraf** [comment]
Request you to create a PR. I just lost track of important bugs this way. :-(
