### ISSUE TITLE
wireless mouse causing error in laptop_mode file

### ISSUE THREAD

**Issue by Bulmer** [rickysarraf/laptop-mode-tools#154]
I had a "/sys/class/power_supply/hidpp_battery_0/present - file not found" error which occurred because I have a wireless usb mouse connected which apparently reports the mouse battery in /sys/class/power_supply/ as "hidpp_battery_0" but does not report it as present because its not locally present. I have temporarily fixed it by placing another check in checkBattery() [L669].
      elif [ ! -f $BATT/present ]; then
        log "VERBOSE" "HID Mouse Battery, skipping."

Could you check that out and maybe add it to the source?

**Comment by rickysarraf** [comment]
What version of `laptop-mode-tools` are you on ? We are already doing a check for that file to determine if we should act on it ?

https://github.com/rickysarraf/laptop-mode-tools/blob/lmt-upstream/usr/sbin/laptop_mode#L759
`				PRESENT=$(cat $BATT/present 2> /dev/null || echo "0")`

**Comment by Bulmer** [comment]
Version 1.72-3 and am running it on Debian Testing.

**Comment by rickysarraf** [comment]
So this is reported and fixed with: 0311b5d69d4b273a53f6f18213a62fba69862f74
I will do a release soon. Meanwhile, you can patch it yourself and the change is just a one-liner.

**Comment by BillyCroan** [comment]
I'm having the same problem, but for me present=1
I don't think it's the intention of laptop-mode-tools to react to peripheral batteries.  So perhaps there's a better way to screen them out.

Why for instnace, are we enumerating /sys/class/power_supply/* when we could enumerate /sys/class/power_supply/BAT* ?

For some context:
`x360:/sys/class/power_supply# ls -l

total 0

lrwxrwxrwx 1 root root 0 Jan 20 09:00 ADP1 -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:1b/PNP0C09:00/ACPI0003:00/power_supply/ADP1

lrwxrwxrwx 1 root root 0 Jan 20 09:00 BAT0 -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:1b/PNP0C09:00/PNP0C0A:00/power_supply/BAT0

lrwxrwxrwx 1 root root 0 Jan 20 09:00 hid-0018:04F3:272D.0001-battery -> ../../devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-2/i2c-ELAN2514:00/0018:04F3:272D.0001/power_supply/hid-0018:04F3:272D.0001-battery

x360:/sys/class/power_supply#x360:/sys/class/power_supply# cd hid-0018\:04F3\:272D.0001-battery

x360:/sys/class/power_supply/hid-0018:04F3:272D.0001-battery# catls

-r--r--r-- 1 root root 4096 Jan 20 09:00 ./capacity                                                Line 1 of 1: 1

lrwxrwxrwx 1 root root 0 Jan 20 09:00 ./device -> ../../../0018:04F3:272D.0001                     symbolic link to directory

drwxr-xr-x 3 root root 0 Jan 20 09:00 ./hwmon5                                                     directory with 2 files (0 hidden) and 1 dirs, containing 9 recursively.

-r--r--r-- 1 root root 4096 Jan 20 10:33 ./model_name                                              Line 1 of 1: ELAN2514:00 04F3:272D

-r--r--r-- 1 root root 4096 Jan 20 10:33 ./online                                                  Line 1 of 1: 1

drwxr-xr-x 2 root root 0 Jan 20 10:33 ./power                                                      directory with 18 files (0 hidden) and 0 dirs, containing 0 recursively.

lrwxrwxrwx 1 root root 0 Jan 20 10:33 ./powers -> ../../../0018:04F3:272D.0001                     symbolic link to directory

-r--r--r-- 1 root root 4096 Jan 20 09:00 ./present                                                 Line 1 of 1: 1

-r--r--r-- 1 root root 4096 Jan 20 09:00 ./scope                                                   Line 1 of 1: Device

-r--r--r-- 1 root root 4096 Jan 20 09:00 ./status                                                  Line 1 of 1: Discharging

lrwxrwxrwx 1 root root 0 Jan 20 09:00 ./subsystem -> ../../../../../../../../../class/power_supply symbolic link to directory

-r--r--r-- 1 root root 4096 Jan 20 09:00 ./type                                                    Line 1 of 1: Battery

-rw-r--r-- 1 root root 4096 Jan 20 09:00 ./uevent                                                  Line 1 of 8: POWER_SUPPLY_NAME=hid-0018:04F3:272D.0001-battery

drwxr-xr-x 2 root root 0 Jan 20 10:33 ./wakeup45                                                   directory with 11 files (0 hidden) and 0 dirs, containing 0 recursively.

x360:/sys/class/power_supply/hid-0018:04F3:272D.0001-battery# `

I believe that hid-0018:04F3:272D.0001 is the battery in my stylus for my stylus-enabled screen.  the hid-0018:04F3:272D.0001 dir was there before I ever bought or used a stylus too.  So there's some ugliness in the driver for that.  But regardless, LMT shouldn't be reacting to stylus batteries.

**Comment by BillyCroan** [comment]
I should also note, that this stylus pen, always reports that it is discharging, 1% remaining.  That doesn't help anything, I'm sure.  Can LMT simply ignore all peripheral batteries?

**Comment by BillyCroan** [comment]
I should also note, that this stylus pen, after the first time i used it after a fresh boot, always reports that it is discharging, 1% remaining.  That doesn't help anything, I'm sure.  Can LMT simply ignore all peripheral batteries?

Also when you print to syslog these warnings:
2024-01-20T12:08:38.150322-06:00 x360 laptop_mode[187670]: WARNING: Battery does not report a capacity. Minimum battery
2024-01-20T12:08:38.150388-06:00 x360 laptop_mode[187670]: charge checking does not work without a design capacity.
2024-01-20T12:08:38.150406-06:00 x360 laptop_mode[187670]: WARNING: Battery does not report a design capacity. Auto hibernation
 
can you include the NAME of the offending battery to narrow down resolution?
