### ISSUE TITLE
installing laptop-mode-tools lets renaming network interfaces fail -- archlinux

### ISSUE THREAD

**Issue by hrehfeld** [rickysarraf/laptop-mode-tools#155]
**Describe the bug**
I'm also running into this: https://bbs.archlinux.org/viewtopic.php?id=252364

After installing laptop-mode-tools, udev can't rename the network interface with 'device or resource busy.'.

**To Reproduce**
1. Install Archlinux
2. configure network using predictable if names
3. install laptop-mode-tools
4. reboot, observe `journalctl -u systemd-udevd` or `sudo udevadm test /sys/class/net/eth0`

**Expected behavior**
nothing. :-)

**Important Information:**
 - Arch
 - zen-kernel 5.5.6
 - laptop-mode-tools 1.73.1-1
- see above archlinux forum post for more info.

**Workaround**
Just uninstall laptop-mode-tools.

**Comment by rickysarraf** [comment]
Yes. I am aware of it. There's a similar bug report on Debian.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=952506
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925944

There's a couple of issues here. Some of it is documented in the bug reports I've mentioned.

* `eth0` used to be a generalized name in the past. So we chose to aggressively use it. THat is not the case any more. Especially with uniquely identifiable persistent names. So, the default has been [dropped](https://github.com/rickysarraf/laptop-mode-tools/commit/84ea165b11f8a0305c88963ea5cc042109f6d5f9)
* Ethernet devices have always had issues. If you go through the bug report on the upstream page as well as the Debian BTS, you'll see the maximum power saving issues with ethernet devices. Infact, ethernet throttling was disabled by default, for Debian for many many years. With the commit mention in the 1st bullet point, this situation too is avoided.
* The last point is about network management tools (NetworkManger etc) failing to act on the device after powersavings are enabled. That is something beyond the scope of laptop-mode-tools. It only does apply power savings, not just to the wired interface but also the wireless interface. If external daemons don't like such change, you can consider disabling the source of the problem (in laptop-mode-tools) or the destination (NM). The latter may be difficult to convince. So, easy route is to disable ethernet module in laptop-mode-tools. Ethernet is uncommon these days and disabling that module (which is what laptop-mode-tools now does by default) is the sensible thing to do today.
