### ISSUE TITLE
how to clean up my system after your scripts...

### ISSUE THREAD

**Issue by grenudi** [rickysarraf/laptop-mode-tools#158]
**Describe the bug**
does nothing.
can not get system back how it was before.

**To Reproduce**
remove laptop-mode (via package manager)

**Expected behavior**
deletes all the crap that was change by these scripts

**Important Information:**
 - Distribution:Void
 - Linux Kernel:5.7.16_1
 - Laptop Mode Tools version:1.73.1_1
 - Desktop Environment:dwm,xinit
 - Relevant System Logs:none
 - Laptop Mode Tools verbose logs:none

**Additional context**
I had my acpid configured (lid, volume btns, etc)
now nothing works, more over, on lid close laptop hibernates twice in a raw..

**Comment by rickysarraf** [comment]
If you installed it through your distribution's package manager, use the same to uninstall it.  There's nothing specific to Laptop Mode Tools here.
