### ISSUE TITLE
Failed in populateValues() when operating on /etc/laptop-mode/conf.d/board-specific

### ISSUE THREAD

**Issue by LorenzoVasi** [rickysarraf/laptop-mode-tools#177]
**Describe the bug**
When i try to modify any option, it doens't work and it makes the following error:
Couldn't apply all request settings
I try to uncheck all settings because i thinked that it was my laptop, but it makes always this error

Applications logs with DEBUG, VERBOSE_OUTPUT enabled:
```bash
Exec with pkexec
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Failed in populateValues() when operating on /etc/laptop-mode/conf.d/board-specific
Couldn't apply setting for checkBox_board-specific
```

**To Reproduce**
//

**Expected behavior**
//

**Screenshots**
![immagine](https://user-images.githubusercontent.com/48059088/156054382-3fac5d1a-8d67-419d-99b0-eacfb311c77e.png)

**Important Information:**
 - Distribution - Debian11 Bullseye
 - Linux Kernel - Linux 5.10.0-11-amd64
 - Laptop Mode Tools version - lastest
 - Desktop Environment, if any - GNOME41 with Wayland
 - Relevant System Logs - Up
 - Laptop Mode Tools verbose logs - Enabled

**Additional context**
//

Thx for all, have a good day :)

**Comment by murray** [comment]
I worked around this issue by deleting the directory: /etc/laptop-mode/conf.d/board-specific
https://github.com/rickysarraf/laptop-mode-tools/issues/178

**Comment by rickysarraf** [comment]
Thank you for reporting this issue. I can confirm the bug.

**Comment by LorenzoVasi** [comment]
No problem, thank u for all your work 😊

Il mer 2 mar 2022, 10:01 Ritesh Raj Sarraf ***@***.***> ha
scritto:
