### ISSUE TITLE
O

### ISSUE THREAD

**Issue by adrielkuek** [rickysarraf/laptop-mode-tools#193]
**Describe the bug**
A clear and concise description of what the bug is.a

**To Reproduce**

**Expected behavior**

**Screenshots**

**Important Information:**
 - Distribution
 - Linux Kernel
 - Laptop Mode Tools version
 - Desktop Environment, if any
 - Relevant System Logs
 - Laptop Mode Tools verbose logs

**Additional context**

**Comment by rickysarraf** [comment]
Closed `......`
