### ISSUE TITLE
Set CPU_GOVERNOR per CPU

### ISSUE THREAD

**Issue by jmaurice** [rickysarraf/laptop-mode-tools#56]
Of course, when you're on AC power, you want your laptop to be in "performance" mode. But when you're on battery, why set *all* CPUs to "ondemand" ? Ideally I would like to have 1 CPU core set to "performance" and the other 7 CPUs set to "ondemand" - is this currently possible somehow or should I look at sending a PR ? Thanks

**Comment by rickysarraf** [comment]
Battery or AC power, ondemand is the most optimal governor is all use cases. There's good reason why it is set as the default in the upstream kernel.

But if you want, you can make the changes. But even before raising the PR, I'd suggest you test it in your environment first.

**Comment by rickysarraf** [comment]
I never heard back from you. Is this still a problem ?

If you are on Intel hardware (most common), this does not even apply. So can you share more details?

**Comment by rickysarraf** [comment]
Closing this bug. Please re-open if you still have the issue.
