### ISSUE TITLE
Uninstalling laptop-mode-tools

### ISSUE THREAD

**Issue by rootd** [rickysarraf/laptop-mode-tools#61]
How to uninstall laptop-mode-tools? Something like an uninstall.sh script would come in handy.

**Comment by rickysarraf** [comment]
This usually was delegated to individual GNU/Linux distributions. While it'd be nice to have something like this, I doubt there are many users. So having an uninstall script is something I don't intend to work any time soon.

What distribution are you on?

**Comment by rootd** [comment]
I am running Ubuntu 16.04 right now

**Comment by rickysarraf** [comment]
I'm not sure what Ubuntu's user interface to install/remove applications is, but you may want to try the following.

```
apt-get remove --purge laptop-mode-tools
```

Since this issue has not much to do with Laptop Mode Tools, and we expect users to use Laptop Mode Tools through a package, I'm closing this bug report.
