### ISSUE TITLE
add start stop programs for terminal blanking

### ISSUE THREAD

**Issue by gavsiu** [rickysarraf/laptop-mode-tools#62]
Is this possible? I have a keyboard with backlight and would like to turn it off when the screen turns off and turn it back on when the screen turns on.

I could use `xset -q`, but there would be a delay as I wouldn't want it querying continuously.

**Comment by rickysarraf** [comment]
On Thu, 2016-04-28 at 09:54 -0700, gavsiu wrote:
> Is this possible? I have a keyboard with backlight and would like to turn it
> off when the screen turns off and turn it back on when the screen turns on.
> I could use xset -q, but there would be a delay as I wouldn't want it querying
> continuously.


What do you mean by screen off ? Are you talking about regular desktop screen
off ? Or are you talking about console terminal blanking ?

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by gavsiu** [comment]
When the screen goes off during idle. Sorry, I thought it was the same.

**Comment by rickysarraf** [comment]
On Sat, 2016-04-30 at 12:56 -0700, gavsiu wrote:
> When the screen goes off during idle. Sorry, I thought it was the same.

Desktop screen idle is controlled by the display server, which typically is
Xorg. That further is controlled by your Desktop Manager, like GNOME, KDE etc.

There's not much Laptop Mode Tools can do here.

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."
