### ISSUE TITLE
cannot shutdown with laptop-mode-tools enabled and kde as DE

### ISSUE THREAD

**Issue by ibok** [rickysarraf/laptop-mode-tools#73]
Kde5 alone shuts down correctly as does using just the terminal with no DE or login manager and laptop-mode-tools enabled (tested several times). However when both are enabled the screen freezes almost always, and nothing happens. Nothing works either.

This applies to the shutdown, logout, and restart functions (but not lock) in both the leave menu and via a terminal window. I am in the power group on my laptop. This issue may not be completely due to laptop-mode-tools as kde seems to have had it for a while.

[dmesg.txt](https://github.com/rickysarraf/laptop-mode-tools/files/460100/dmesg.txt)
/usr/src/linux/.config: [kernelconfig.txt](https://github.com/rickysarraf/laptop-mode-tools/files/460109/kernelconfig.txt)

Contact me at ilhanbok@outlook.com if you would like more information or for discussion.

**Comment by rickysarraf** [comment]
Yes. I'm confident LMT doesn't do any such change causing such problem. It must be elsewhere. I'll close this bug but if you have enough information, please feel free to re-open it.
