### ISSUE TITLE
GUI fails to start: "name 'os' is not defined"

### ISSUE THREAD

**Issue by sebastianst** [rickysarraf/laptop-mode-tools#79]
Upon starting the gui, I get the following error:

```
$ lmt-gui            
Using PyQt4
Traceback (most recent call last):
  File "/usr/bin/lmt-gui", line 31, in <module>
    os.putenv('QT_X11_NO_MITSHM', "1")
NameError: name 'os' is not defined
```

I am on Arch Linux and installed LMT via the [AUR package](https://aur.archlinux.org/packages/laptop-mode-tools/). The optional dependency `python2-pyside` is also installed.

**Comment by rickysarraf** [comment]
It is fixed in my repo and slated for next release. You can check in the
git repository. It is a one line fix.

I'm sorry I'm unable to pinpoint the fix, because my laptop charger went
bad today and my laptop has drained out

s3nt fr0m a $martph0ne, excuse typ0s

**Comment by rickysarraf** [comment]
This commit: https://github.com/rickysarraf/laptop-mode-tools/commit/976be20c0f5bc8078952c0a9a0661c8fb936f994 fixes the problem.

**Comment by rickysarraf** [comment]
1.71 is released now.
