### ISSUE TITLE
No Debian package available on website

### ISSUE THREAD

**Issue by floeschie** [rickysarraf/laptop-mode-tools#89]
In the README file, Debian users are suggested to use the Debian package available on the website:

> Debian users, please install the Debian package that can be found on the home page and in the unstable repository!

However, I can't seem to find a link or download section on the [website](http://rickysarraf.github.io/laptop-mode-tools/).

**Comment by rickysarraf** [comment]
Thanks for the report. You should be able to get the correct link referenced in the README now.
